[build]
  functions = "netlify/functions"
  publish = "public"

[build.environment]
  PYTHON_VERSION = "3.12"

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/api/:splat"
  status = 200
  force = true
